// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnqWOlHaGE6KZjr2Dc3AzmU0NzStBuIjw',
    appId: '1:865135203621:web:f02e835fa373c9dd4b36cc',
    messagingSenderId: '865135203621',
    projectId: 'crudcarros-ead9c',
    authDomain: 'crudcarros-ead9c.firebaseapp.com',
    storageBucket: 'crudcarros-ead9c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfpUQoRRTWfGYzIj2UmdSqqMorOf9YjCU',
    appId: '1:865135203621:android:6bf7e8439233c2094b36cc',
    messagingSenderId: '865135203621',
    projectId: 'crudcarros-ead9c',
    storageBucket: 'crudcarros-ead9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMZAFEnt9aOsbfw-qIIxtbEl5vgGt0YxE',
    appId: '1:865135203621:ios:c40dbd9fdbdfd44b4b36cc',
    messagingSenderId: '865135203621',
    projectId: 'crudcarros-ead9c',
    storageBucket: 'crudcarros-ead9c.appspot.com',
    iosBundleId: 'com.example.crudcarros',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMZAFEnt9aOsbfw-qIIxtbEl5vgGt0YxE',
    appId: '1:865135203621:ios:c40dbd9fdbdfd44b4b36cc',
    messagingSenderId: '865135203621',
    projectId: 'crudcarros-ead9c',
    storageBucket: 'crudcarros-ead9c.appspot.com',
    iosBundleId: 'com.example.crudcarros',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnqWOlHaGE6KZjr2Dc3AzmU0NzStBuIjw',
    appId: '1:865135203621:web:e3450021d4f852ba4b36cc',
    messagingSenderId: '865135203621',
    projectId: 'crudcarros-ead9c',
    authDomain: 'crudcarros-ead9c.firebaseapp.com',
    storageBucket: 'crudcarros-ead9c.appspot.com',
  );
}
